import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "./providers";
import BottomNabar from "@/components/BottomNavbar/bottomNavbar";

const newSansFont = localFont({
  src: [
    // {
    //   path: "./fonts/Rubik-Regular.ttf",
    //   weight: "400",
    //   style: "normal",
    // },
    // {
    //   path: "./fonts/Rubik-Medium.ttf",
    //   weight: "500",
    //   style: "normal",
    // },
    // {
    //   path: "./fonts/Rubik-SemiBold.ttf",
    //   weight: "700",
    //   style: "normal",
    // },
    // {
    //   path: "./fonts/Rubik-Bold.ttf",
    //   weight: "900",
    //   style: "normal",
    // },
    {
      path: "./fonts/NeoSansArabic.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NeoSansArabicBold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  // variable: "--font-rubik",
  variable: "--font-NeoSans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${newSansFont.variable} antialiased`}>
        <ReactQueryProvider>
          {children}
          <BottomNabar />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
